NCBCNet/urls.py
from django.contrib import admin
from django.template.defaulttags import url
from django.urls import path,include,re_path
from server import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.views import serve
# import notifications.urls

urlpatterns = [
    path('favicon.ico', serve, {'path': 'server/favicon.ico'}),
    path('admin/', admin.site.urls),
    path('',views.index),
    path('server/', include('server.urls', namespace='server')),
    path('article/',include('article.urls',namespace='article')),
    path('usermanage/',include('usermanage.urls',namespace='usermanage')),
    path('comment/', include('comment.urls', namespace='comment')),
    path(r'mdeditor/', include('mdeditor.urls')),
    # path('^inbox/notifications/', include(notifications.urls, namespace='notifications')),

]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/urls.py
from django.contrib import admin
from django.urls import path

from server import views

app_name = "server"
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('easter_egg/114514/1/',views.easter_egg_1,name='easter_egg_1'),
]

usermanage/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "usermanage"
urlpatterns = [
    path("login/",views.user_login,name="login"),
    path("logout/",views.user_logout,name="logout"),
    path("register/",views.user_register,name="register"),
    path("delete/<int:id>/",views.user_delete,name="delete"),
    path("edit/<int:id>/",views.edit_profile,name="edit_profile"),
]

usermanage/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    phone = models.CharField(max_length=20,blank=True)
    avatar = models.ImageField(upload_to='avatar/%Y%m%d/', blank=True)
    bio = models.TextField(max_length=500, blank=True)
    def __str__(self):
        return 'user {}'.format(self.user.username)

# @receiver(post_save, sender=User)
# def create_user_profile(sender, instance, created, **kwargs):
#     if created:
#         Profile.objects.create(user=instance)
#
# @receiver(post_save, sender=User)
# def save_user_profile(sender, instance, **kwargs):
#     instance.profile.save()

usermanage/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Profile


class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField()

class UserRegisterForm(forms.ModelForm):
    password = forms.CharField()
    password2 = forms.CharField()
    class Meta:
        model = User
        fields = {'username','email'}

    def clean_password2(self):
        data = self.cleaned_data
        if data.get('password') == data.get('password2'):
            return data.get('password')
        else:
            return forms.ValidationError('密码不一致！')

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = {'phone','avatar','bio'}

usermanage/views.py
from lib2to3.fixes.fix_input import context

from django.shortcuts import render,redirect
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from .forms import UserLoginForm,UserRegisterForm,ProfileForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .models import Profile
# Create your views here.

def user_register(request):
    if request.method == 'POST':
        form = UserRegisterForm(data=request.POST)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(form.cleaned_data['password'])
            new_user.save()
            login(request, new_user)
            return redirect('server:index')
        else:
            return HttpResponse("输入有误")
    elif request.method == 'GET':
        form = UserRegisterForm()
        context = {'form': form}
        return render(request,'usermanage/register.html',context)
    else:
        return HttpResponse("仅允许GET或POST")
def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = authenticate(username=data['username'], password=data['password'])
            if user:
                login(request, user)
                return redirect('server:index')
            else:
                return HttpResponse("账号或密码有误")
        else:
            return HttpResponse("输入不合法")
    elif request.method == 'GET':
        form = UserLoginForm()
        context = {'form': form}
        return render(request,'usermanage/login.html',context)
    else:
        return HttpResponse("不是GET或POST请求")

def user_logout(request):
    logout(request)
    return redirect('server:index')

@login_required(login_url='usermanage:login')
def user_delete(request,id):
    if request.method == 'POST':
        user = User.objects.get(id=id)
        if request.user == user:
            logout(request)
            user.delete()
            return redirect('server:index')
        else:
            return HttpResponse("你没有删除权限")
    else:
        return HttpResponse("仅允许POST请求")

@login_required(login_url='usermanage:login')
def edit_profile(request,id):
    user = User.objects.get(id=id)
    # user_id 是 OneToOneField 自动生成的字段
    # profile = Profile.objects.get(user_id=id)
    if Profile.objects.filter(user_id=id).exists():
        profile = Profile.objects.get(user_id=id)
    else:
        profile = Profile.objects.create(user=user)
    if request.method == 'POST':
        if request.user != user:
            return HttpResponse("你没有权限")
        profile_form = ProfileForm(request.POST,request.FILES)
        if profile_form.is_valid():
            profile_cd = profile_form.cleaned_data
            profile.phone = profile_cd['phone']
            profile.bio = profile_cd['bio']
            if 'avatar' in request.FILES:
                profile.avatar = profile_cd['avatar']
            profile.save()
            return redirect('usermanage:edit_profile',id=id)
        else:
            return HttpResponse("注册表单输入有误。请重新输入~")
    elif request.method == 'GET':
        profile_form = ProfileForm()
        context = {'profile_form': profile_form,'user':user,'profile':profile}
        return render(request,'usermanage/profile.html',context)
    else:
        return HttpResponse("请使用GET或POST请求数据")

templates/usermanage/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-5 mt-5">
                <h1>登录</h1>
                <form method="POST" action=".">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="username">账号</label>
                        <input type="text" class="form-control" id="username" name="username" placeholder="输入用户名">
                    </div>
                    <small class="form-text text-muted m-lg-1">
                        还没有账号？
                        <a href="{% url 'usermanage:register' %}" style="color: cornflowerblue;">注册</a>
                    </small>
                    <br>
                    <br>
                    <div class="form-group">
                        <label for="password">密码</label>
                        <input type="password" class="form-control" id="password" name="password" placeholder="输入密码">
                    </div>
                    <br>
                    <br>
                    <button type="submit" class="btn btn-primary">提交</button>
                </form>

            </div>
        </div>
    </div>
{% endblock %}

templates/usermanage/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12 mt-5">
                <div class="col-md-4"><h1>{{ user.username }}</h1></div>
                <br>
                {% if profile.avatar %}
                    <img src="{{profile.avatar.url}}" style="max-width: 20%; border-radius: 15%;" class="col-md-4" alt="{{ user.username }}">
                {% else %}
                    <h5 class="col-md-4">暂无头像</h5>
                {% endif %}
                <br>
                <br>
                <form method="POST" action="." enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="input-group">
                        <label for="avatar" class="input-group-text">上传头像</label>
                        <input type="file" class="form-control" id="avatar" name="avatar">
                    </div>
                    <br>
                    <div class="form-group">
                        <label for="phone">电话</label>
                        <input type="text" class="form-control" id="phone" name="phone" value="{{ profile.phone }}">
                    </div>
                    <br>
                    <div class="form-group col-md-4">
                        <label for="bio">简介</label>
                        <textarea type="text" class="form-control" id="bio" name="bio" rows="12">{{ profile.bio }}</textarea>
                    </div>
                    <br>
                    <br>
                    <button type="submit" class="btn btn-primary">提交</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/usermanage/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12 mt-5">
                <h1>注册</h1>
                <form method="POST" action=".">
                    {% csrf_token %}
                    <div class="form-group col-md-4">
                        <label for="username">用户名</label>
                        <input type="text" class="form-control" id="username" name="username" required>
                    </div>
                    <div class="form-group col-md-4">
                        <label for="email">邮箱</label>
                        <input type="text" class="form-control" id="email" name="email">
                    </div>
                    <div class="form-group col-md-4">
                        <label for="password">密码</label>
                        <input type="password" class="form-control" id="password" name="password" required>
                    </div>
                    <div class="form-group col-md-4">
                        <label for="password2">重复密码</label>
                        <input type="password" class="form-control" id="password2" name="password2" required>
                    </div>
                    <br>
                    <br>
                    <button type="submit" class="btn btn-primary">提交</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}