NCBCNet/urls.py
from django.contrib import admin
from django.template.defaulttags import url
from django.urls import path,include,re_path
from server import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.views import serve
# import notifications.urls

urlpatterns = [
    path('favicon.ico', serve, {'path': 'server/favicon.ico'}),
    path('admin/', admin.site.urls),
    path('',views.index),
    path('server/', include('server.urls', namespace='server')),
    path('article/',include('article.urls',namespace='article')),
    path('usermanage/',include('usermanage.urls',namespace='usermanage')),
    path('comment/', include('comment.urls', namespace='comment')),
    path(r'mdeditor/', include('mdeditor.urls')),
    # path('^inbox/notifications/', include(notifications.urls, namespace='notifications')),

]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/urls.py
from django.contrib import admin
from django.urls import path

from article import views

app_name = "article"
urlpatterns = [
    path('', views.article_list, name='list'),
    path('article_detail/<int:id>/', views.article_detail, name='article_detail'),
    path('article_create/',views.article_create, name='article_create'),
    path('article_update/<int:id>/', views.article_update, name='article_update'),
    path('article_delete/<int:id>/', views.article_delete, name='article_delete'),
    path('increase_likes/<int:id>/',views.IncreaseLikesView.as_view(),name='increase_likes')
]

server/urls.py
from django.contrib import admin
from django.urls import path

from server import views

app_name = "server"
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('easter_egg/114514/1/',views.easter_egg_1,name='easter_egg_1'),
]

usermanage/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "usermanage"
urlpatterns = [
    path("login/",views.user_login,name="login"),
    path("logout/",views.user_logout,name="logout"),
    path("register/",views.user_register,name="register"),
    path("delete/<int:id>/",views.user_delete,name="delete"),
    path("edit/<int:id>/",views.edit_profile,name="edit_profile"),
]

templates/back_to_top_func.html
<!-- 参考了 鹦鹉 的代码，在此致谢 -->
<!-- https://ezbox.idv.tw/131/back-to-top-button-without-images -->

<button type="button" id="BackTop" class="toTop-arrow" style="z-index: 100;"></button>

<script>
    // 向上滚动的函数
    $(function () {
        $('#BackTop').click(function () {
            $('html,body').animate({scrollTop: 0}, 500);
        });
        $(window).scroll(function () {
            if ($(this).scrollTop() > 300) {
                $('#BackTop').fadeIn(300);
            } else {
                $('#BackTop').stop().fadeOut(300);
            }
        }).scroll();
    });
</script>

<style>
    /* 按钮边框的大小、位置、样式 */
    .toTop-arrow {
        width: 3.5rem;
        height: 3.5rem;
        padding: 0;
        margin: 0;
        border: 0;
        border-radius: 33%;
        opacity: 0.7;
        background: black;
        cursor: pointer;
        position: fixed;
        right: 1.5rem;
        bottom: 1.5rem;
        display: none;
    }

    /* 绘制按钮中的向上箭头 */
    .toTop-arrow::before, .toTop-arrow::after {
        width: 31px;
        height: 7px;
        border-radius: 3px;
        background: orange;
        position: absolute;
        content: "";
    }

    .toTop-arrow::before {
        transform: rotate(-45deg) translate(0, -50%);
        left: 0.4rem;
    }

    .toTop-arrow::after {
        transform: rotate(45deg) translate(0, -50%);
        right: 0.4rem;
    }

    /* 取消点击按钮时的聚焦 */
    .toTop-arrow:focus {
        outline: none;
    }
</style>

templates/base.html
{% load static %}
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <title>NCNet-南城网 {% block title %}{% endblock %}</title>
    <link rel="shortcut icon" href="{% static 'server/favicon.ico' %}" />
    <link rel="stylesheet" href="{% static 'prism/prism.css' %}"/>
    <link rel="stylesheet" href="{% static 'editor.md-master/css/editormd.css' %}"/>
    {% block head %}{% endblock head %}
    <style>
        [data-bs-theme="purple"] {
            background-color: #6f42c1;
        }
        html, body {
            height: 100%;
            margin: 0;
        }

        #wrapper {
            min-height: 100%;
            margin-bottom:  -60px;
        }

        .footer {
            background-color: #6f42c1;
            height: 60px;
        }
        .custom-navbar {
            background-color: #6f42c1;
        }
        .custom-navbar a {
            color: white;
        }

    </style>
{#    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">#}
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.14.0/css/all.min.css">
    <link rel="stylesheet" href="{% static 'md_css/gh_dark.css' %}">
</head>

<body>
    {% include 'header.html' %}
    <div id="wrapper">
        {% block content %}{% endblock content %}
    </div>
    {% include 'footer.html' %}
    <script src="{% static 'jquery/jquery-3.7.1.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'layer/layer.js' %}"></script>
    <script src="{% static 'editor.md-master/editormd.js' %}"></script>
    <script src="{% static 'ckeditor/ckeditor/plugins/prism/lib/prism/prism_patched.min.js' %}"></script>
    {% include 'back_to_top_func.html' %}
</body>
{% block script %}{% endblock script %}
</html>

templates/footer.html
{% load static %}
<!-- Footer -->
<div class="mt-5">
    <br>
    <br>
</div>
<footer class="py-3 footer">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; www.ncnet.com 2024 Alpha v0.1</p>
    </div>
</footer>

templates/header.html
<!-- 定义导航栏 -->
{% load static %}
<nav class="navbar navbar-expand-lg sticky-top custom-navbar" data-bs-theme="dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">NCNet</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'article:list' %}">论坛</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">学习</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">云盘</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'server:about' %}">关于</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                           aria-expanded="false">
                            {{ user.username }}
                        </a>
                        <div class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDropdown"
                             style="background-color: #6f42c1;">
                            <a class="dropdown-item" href="{% url 'usermanage:edit_profile' user.id %}">个人信息</a>
                            <a class="dropdown-item" href="/admin">后台管理</a>
                            <a class="dropdown-item" href="{% url 'article:article_create' %}">写文章</a>
                            <hr class="dropdown-divider">
                            <a class="dropdown-item" href="{% url 'usermanage:logout' %}">退出登录</a>
                            <a class="dropdown-item" href="#" style="color: #dc3545;"
                               onclick="user_delete()">删除用户</a>
                            <form
                                    style="display:none;"
                                    id="user_delete"
                                    action="{% url 'usermanage:delete' user.id %}"
                                    method="POST"
                            >
                                {% csrf_token %}
                                <button type="submit">发送</button>
                            </form>
                        </div>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'usermanage:login' %}">登录</a>
                    </li>
                {% endif %}

            </ul>
        </div>
    </div>
</nav>
{% if user.is_authenticated %}
    <script>
        function user_delete() {
            // 调用layer弹窗组件
            layer.open({
                title: "确认删除",
                content: "确认删除用户资料吗？",
                yes: function (index, layero) {
                    $('form#user_delete button').click();
                    layer.close(index);
                },
            })
        }
    </script>
{% endif %}