NCBCNet/urls.py
from django.contrib import admin
from django.template.defaulttags import url
from django.urls import path,include,re_path
from server import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.views import serve
# import notifications.urls

urlpatterns = [
    path('favicon.ico', serve, {'path': 'server/favicon.ico'}),
    path('admin/', admin.site.urls),
    path('',views.index),
    path('server/', include('server.urls', namespace='server')),
    path('article/',include('article.urls',namespace='article')),
    path('usermanage/',include('usermanage.urls',namespace='usermanage')),
    path('comment/', include('comment.urls', namespace='comment')),
    path(r'mdeditor/', include('mdeditor.urls')),
    # path('^inbox/notifications/', include(notifications.urls, namespace='notifications')),

]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/urls.py
from django.contrib import admin
from django.urls import path

from article import views

app_name = "article"
urlpatterns = [
    path('', views.article_list, name='list'),
    path('article_detail/<int:id>/', views.article_detail, name='article_detail'),
    path('article_create/',views.article_create, name='article_create'),
    path('article_update/<int:id>/', views.article_update, name='article_update'),
    path('article_delete/<int:id>/', views.article_delete, name='article_delete'),
    path('increase_likes/<int:id>/',views.IncreaseLikesView.as_view(),name='increase_likes')
]

comment/urls.py
from django.urls import path
from . import views

app_name= "comment"
urlpatterns = [
    path('post-comment/<int:article_id>/', views.post_comment, name='post_comment'),
    path('post-comment/<int:article_id>/<int:parent_comment_id>/',views.post_comment, name='comment_reply')
]

server/urls.py
from django.contrib import admin
from django.urls import path

from server import views

app_name = "server"
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('easter_egg/114514/1/',views.easter_egg_1,name='easter_egg_1'),
]

usermanage/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "usermanage"
urlpatterns = [
    path("login/",views.user_login,name="login"),
    path("logout/",views.user_logout,name="logout"),
    path("register/",views.user_register,name="register"),
    path("delete/<int:id>/",views.user_delete,name="delete"),
    path("edit/<int:id>/",views.edit_profile,name="edit_profile"),
]

article/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from mdeditor.fields import MDTextField
from taggit.managers import TaggableManager
from PIL import Image

# Create your models here.
class Articletest(models.Model):
    title = models.CharField(max_length=100)
    content = MDTextField()
class ArticleColumn(models.Model):
    """
    栏目的Model
    """
    title = models.CharField(max_length=100,blank=True)
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

class Article(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    avatar = models.ImageField(upload_to='article/%Y%m%d/', blank=True)
    kinds = {
        "at": "article",
        "ds": "discussions",
    }
    kind = models.CharField(
        max_length=2,
        choices=kinds,
        default="at",
    )

    def save(self,*args ,**kwargs):
        article = super(Article,self).save(*args,**kwargs)
        if self.avatar and not kwargs.get('update_fields'):
            image = Image.open(self.avatar)
            (x,y) = image.size
            new_x = 400
            new_y = int(new_x*y/x)
            resized_image = image.resize((new_x,new_y),Image.ANTIALIAS) # Pillow新版无法使用
            resized_image.save(self.avatar.path)
        return article
    column = models.ForeignKey(ArticleColumn,null=True,blank=True,on_delete=models.CASCADE,related_name='article')
    tags = TaggableManager(blank=True)
    likes = models.PositiveIntegerField(default=0)
    content = MDTextField()
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)
    total_views = models.PositiveIntegerField(default=0)
    class Meta:
        ordering = ('-created',) # -created倒序排序
    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('article:article_detail',args=[self.id])

article/forms.py
from django import forms
from .models import Article

class ArticlePostForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'content','tags','avatar']

article/views.py
from anyio.abc import value
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.views import View

from .models import Article, ArticleColumn
import markdown
from django.shortcuts import redirect
from django.http import HttpResponse
from .forms import ArticlePostForm
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.db.models import Q
from comment.models import Comment
from comment.forms import CommentForm

# Create your views here.

def article_list(request):
    search = request.GET.get('search')
    order = request.GET.get('order')
    column = request.GET.get('column')
    tag = request.GET.get('tag')

    article_list = Article.objects.all()

    if search:
        article_list = article_list.filter(
            Q(title__icontains=search) |
            Q(body__icontains=search)
        )
    else:
        search = ''

        # 栏目查询集
    if column is not None and column.isdigit():
        article_list = article_list.filter(column=column)

        # 标签查询集
    if tag and tag != 'None':
        article_list = article_list.filter(tags__name__in=[tag])

        # 查询集排序
    if order == 'total_views':
        article_list = article_list.order_by('-total_views')

    paginator = Paginator(article_list, 10)
    page = request.GET.get('page')
    articles = paginator.get_page(page)

    context = {"articles":articles,'order':order,'search':search}
    return render(request, 'article/list.html', context)


def article_detail(request, id):
    article = Article.objects.get(id=id)
    comments = Comment.objects.filter(article=id)
    article.total_views += 1
    article.save(update_fields=['total_views'])
    comment_form = CommentForm()
    md = markdown.Markdown(extensions=[
                                            'markdown.extensions.extra',
                                            'markdown.extensions.codehilite',
                                            'markdown.extensions.toc',
                                        ]
                                        )
    article.content = md.convert(article.content)
    context = {'article': article,'toc':md.toc,'comments':comments,'comment_form':comment_form,}
    return render(request, 'article/detail.html', context)


@login_required(login_url='usermanage:login')
def article_create(request):
    if request.method == 'POST':
        form = ArticlePostForm(request.POST,request.FILES)
        if form.is_valid():
            new_article = form.save(commit=False)
            new_article.author = User.objects.get(id=request.user.id)
            if request.POST['column'] != 'none':
                new_article.column = ArticleColumn.objects.get(id=request.POST['column'])
            new_article.save()
            form.save_m2m()
            return redirect('article:list')
        else:
            return HttpResponse(form.errors, status=400)
    else:
        article_form = ArticlePostForm()
        columns = ArticleColumn.objects.all()
        context = {'article_form': article_form,'columns':columns}
        return render(request, 'article/create_article.html', context)


@login_required(login_url='usermanage:login')
def article_update(request, id):
    article = Article.objects.get(id=id)
    if request.user == article.author:
        if request.method == 'POST':
            form = ArticlePostForm(data=request.POST)
            form.content = request.POST['content']
            if form.is_valid():
                article.title = request.POST['title']
                article.content = request.POST['content']
                if request.POST['column'] != 'none':
                    article.column = ArticleColumn.objects.get(id=request.POST['column'])
                else:
                    article.column = None
                if request.POST['tags'] != '':
                    pass
                else:
                    pass
                article.save()
                return redirect('article:article_detail', id=id)
            else:
                return HttpResponse("表单有误")
        else:
            article_form = ArticlePostForm(initial={'content':article.content})
            columns = ArticleColumn.objects.all()
            tagson = ''
            for tag in article.tags.all():
                tagson += tag.name + ','
            tagson = tagson[:-1]
            context = {'article_form': article_form, 'article': article,'columns':columns,"tags":tagson}
            return render(request, 'article/updata_article.html', context)
    else:
        return HttpResponse("你没有权限")


@login_required(login_url='usermanage:login')
def article_delete(request, id):
    article = Article.objects.get(id=id)
    if request.user == article.author:
        if request.method == 'POST':
            article.delete()
            return redirect('article:list')
        else:
            return HttpResponse('仅允许POST请求')
    else:
        return HttpResponse("你没有权限")


class IncreaseLikesView(View):
    def post(self, request, *args, **kwargs):
        article = Article.objects.get(id=kwargs.get('id'))
        article.likes +=1
        article.save()
        return HttpResponse('success')

templates/article/create_article.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    创建文章
{% endblock %}
{% block content %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-12">
                <form method="POST" action="." enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="title" class="form-label">文章标题</label>
                        <input type="text" class="form-control" id="title" name="title">
                    </div>
                    <br>
                    <div class="form-group">
                        <label for="avatar" class="form-label">标题图</label>
                        <input type="file" class="form-control" name="avatar" id="avatar">
                    </div>
                    <br>
                    <div class="form-group">
                        <label for="column">栏目</label>
                        <select class="form-select" id="column" name="column">
                            <option value="none">请选择栏目...</option>
                            {% for column in columns %}
                                <option value="{{ column.id }}">{{ column }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <br>
                    <div class="form-group">
                        <label for="tags">标签</label>
                        <input type="text" class="form-control col-3" id="tags" name="tags">
                    </div>
                    <br>
                    <div class="form-group">
                        <label for="content" class="form-label">文章内容</label>
                        {{ article_form.media }}
                        {{ article_form.content }}
                    </div>
                    <br>
                    <button type="submit" class="btn btn-primary">提交</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/article/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    {{ article.title }}
{% endblock %}
{% load mptt_tags %}
{% load article_filters_and_tags %}
{% block head %}
    <style>
    .sidebar{
        will-change: min-height;
    }

    .sidebar__inner{
        transform: translate(0, 0);
        transform: translate3d(0, 0, 0);
        will-change: position, transform;
    }
    img{
        width: 100%;
        object-fit: contain;
        border-radius: 20px;
    }
    </style>
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-9" id="main_content">
                <h1 class="col-12 mt-4 mb-4">{{ article.title }}</h1>
                <div class="col-12 alert alert-primary">
                    <div>
                        作者: {{ article.author }}
                        {% if user == article.author %}
                            . <a href="#" onclick="confirm_delete()">删除</a>
                            . <a href="{% url 'article:article_update' article.id %}">编辑</a>
                            <form style="display:none;"
                                    id="safe_delete"
                                    action="{% url 'article:article_delete' article.id %}"
                                    method="POST">
                                {% csrf_token %}
                                <button type="submit">发送</button>
                            </form>
                        {% endif %}
                    </div>
                    <div>
                        浏览量: {{ article.total_views }}
                    </div>
                </div>
                <div class="col-12" style="word-wrap: break-word;max-width: 100%">
                    {{ article.content | safe }}
                </div>
                <div class="mt-4">
                    <button class="btn btn-outline-danger" type="button" onclick="validate_is_like('{% url 'article:increase_likes' article.id %}',{{ article.id }},{{ article.likes }})">
                        <span>点赞</span>
                        <span>
                            <i class="fas fa-heart"></i>
                        </span>
                        <span id="likes_number">
                            {{ article.likes }}
                        </span>
                    </button>
                </div>
                <hr>
                {% if user.is_authenticated %}
                    <div>
                        <form action="{% url 'comment:post_comment' article.id %}" method="POST">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="content">
                                    <strong>
                                        我也要发言：
                                    </strong>
                                </label>
{#                                <textarea#}
{#                                        type="text"#}
{#                                        class="form-control"#}
{#                                        id="content"#}
{#                                        name="content"#}
{#                                        rows="2"></textarea>#}
                                <div>
                                    {{ comment_form.media }}
                                    {{ comment_form.content }}
                                </div>
                            </div>
                            <!-- 提交按钮 -->
                            <button type="submit" class="btn btn-primary mt-2">发送</button>
                        </form>
                    </div>
                    <br>
                {% else %}
                    <br>
                    <h5>
                        请<a href="{% url 'usermanage:login' %}">登录</a>后回复
                    </h5>
                    <br>
                {% endif %}
                <!-- 显示评论 -->
                <h4>共有{{ comments.count }}条评论</h4>
                <div class="row">
                    {% recursetree comments %}
                        {% with comment=node %}
                            <div class="{% if comment.reply_to %}
                                        offset-1 col-11
                                        {% else %}
                                        col-12
                                        {% endif %}">
                                <hr> <!-- 子评论不应有hr -->
                                <p>
                                    <strong style="color: cornflowerblue;">
                                        {{ comment.user }}
                                    </strong>

                                    {% if comment.reply_to %}
                                        <i class="far fa-arrow-alt-circle-right"
                                           style="color: mediumpurple;"></i>
                                        <strong style="color: cornflowerblue;">
                                            {{ comment.reply_to }}
                                        </strong>
                                    {% endif %}
                                </p>
                                <div>{{ comment.content | safe }}</div>
                                <div>
                                    <span style="color: gray">
                                        {{ comment.created|date:"Y-m-d H:i" }}
                                    </span>
                                    {% if user.is_authenticated %}
                                        <button type="button" class="btn btn-light btn-sm text-muted" onclick="load_modal({{ article.id }},{{ comment.id }})">回复</button>
                                    {% else %}
                                        <a class="btn btn-light btn-sm text-muted" href="{% url 'usermanage:login' %}">回复</a>
                                    {% endif %}
                                </div>
                            
                                <!-- Modal -->
                                <div class="modal fade" id="comment_{{ comment.id }}" tabindex="-1" role="dialog" aria-labelledby="CommentModelCenter" aria-hidden="true">
                                    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                                        <div class="modal-content" style="height: 480px">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalCenterTitle">回复 {{ comment.user }}: </h5>
                                            </div>
                                            <div class="modal-content" id="modal_content_{{ comment.id }}"></div>
                                        </div>
                                    </div>
                                </div>
                                {% if not comment.is_leaf_node %}
                                    <div class="children">
                                        {{ children }}
                                    </div>
                                {% endif %}
                            </div>
                    {% endwith %}
                    {% endrecursetree %}
                </div>
            </div>
            <div id="sidebar" class="sidebar col-3 mt-lg-4">
                    <div class="sidebar__inner">
                        <h4><strong>目录</strong></h4>
                        <hr>
                        <div>
                            {{ toc | safe }}
                        </div>
                    </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block script %}
    <script src="{% static 'sticky_sidebar/jquery.sticky-sidebar.min.js' %}"></script>
    <script type="text/javascript">
        $('#sidebar').stickySidebar({
            topSpacing: 80,
            bottomSpacing: 80,
        });
    </script>
    <script>
        // 加载 modal
        function load_modal(article_id, comment_id) {
            let modal_content = '#modal_content_' + comment_id;
            let modal_id = '#comment_' + comment_id;
            
            // 加载编辑器
            if ($(modal_content).children().length === 0) {
                let content = '<iframe src="/comment/post-comment/' + 
                    article_id + 
                    '/' + 
                    comment_id + 
                    '/"' + 
                    ' frameborder="0" style="width: 100%; height: 480px" ></iframe>';
                $(modal_content).append(content);
            }
    
            $(modal_id).modal('show');
        }
        // 删除文章的函数
        function confirm_delete() {
            // 调用layer弹窗组件
            layer.open({
                // 弹窗标题
                title: "确认删除",
                // 正文
                content: "确认删除这篇文章吗？",
                // 点击确定按钮后调用的回调函数
                yes: function (index, layero) {
                    // 指定应当前往的 url
                    $('form#safe_delete button').click();
                    layer.close(index);
                },
            })
        }
    </script>
    <script src="{% static 'csrf.js' %}"></script>
    <script>
        function  validate_is_like(url,id,likes) {
            let storage = window.localStorage;
            const storage_str_data = storage.getItem("NCNet_data");
            let storage_json_data = JSON.parse(storage_str_data);
            if (!storage_json_data) {
                storage_json_data = {}
            }
            const status = check_status(storage_json_data,id);
            if (status) {
                layer.msg('已经点过赞了哟~');
                return;
            } else {
                $('span#likes_number').text(likes+1).css('color','#dc3545');
            }
            $.post(
                url,
                {},
                function (result) {
                    if (result==='success') {
                        try {
                            storage_json_data[id] = true;
                        } catch (e) {
                            window.localStorage.clear();
                        }
                        const d = JSON.stringify(storage_json_data)
                        try {
                            storage.setItem("NCNet_data",d);
                        }catch (e) {
                            if (e.code===22) {
                                window.localStorage.clear()
                                storage.setItem("NCNet_data",d);
                            }
                        }
                    } else {
                        layer.msg("与服务器通信失败..过一会儿再试试呗~")
                    }
                }
            )
        }
        function check_status(data,id) {
            try {
                if(id in data && data[id]) {
                    return true;
                }else{
                    return false;
                }
            }catch (e){
                window.localStorage.clear()
                return flase;
            }
        }
    </script>
    <script>
        $(".django-ckeditor-widget").removeAttr('style');
    </script>
{% endblock %}

templates/article/list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    论坛
{% endblock %}
{% load article_filters_and_tags %}
{% block content %}
    <div class="container">
        <div class="col mt-5">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="{% url 'article:list' %}?search={{ search }}&column={{ column }}&tag={{ tag }}">
                            最新
                        </a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="{% url 'article:list' %}?order=total_views&search={{ search }}&column={{ column }}&tag={{ tag }}">
                            最热
                        </a>
                    </li>
                </ol>
            </nav>
        </div>
        <div class="row">
            <div class="col-auto mr-auto">
            <form class="form-inline" >
                <label class="sr-only"></label>
                <input type="text" 
                    class="form-control mb-2 mr-sm-2" 
                    name="search" 
                    placeholder="搜索文章..." 
                    required
                >
            </form>
            </div>
        </div>
        {% if search %}
            {% if articles %}
                <h4><span style="color: red">"{{ search }}"</span>的搜索结果如下:</h4>
                <hr>
            {% else %}
                <h4>暂无<span style="color: red">"{{ search }}"</span>有关的文章。</h4>
                <hr>
            {% endif %}
        {% endif %}
        <div class="row mt-2">
        {% for article in articles %}
            {% if article.avatar %}
                <div class="col-3">
                    <img src="{{ article.avatar.url }}" alt="avatar" style="max-width: 100%;border-radius: 20px;max-height: 90%">
                </div>
            {% endif %}
            <div class="col-9">
                {% if article.column %}
                    <a role="button" class="btn btn-sm mb-2 btn-success" href="{% url 'article:list' %}?column={{ article.column.id }}">
                        {{ article.column }}
                    </a>
                {% endif %}
                <span>
                    {%  for tag in article.tags.all %}
                        <a href="{% url 'article:list' %}?tag={{ tag }}" class="badge badge-secondary" style="color: gray;">
                            {{ tag }}
                        </a>
                    {% endfor %}
                </span>
                <h4>
                    <b>
                        <a href="{% url 'article:article_detail' article.id %}" style="color: black;word-wrap: break-word;">
                            {{ article.title }}
                        </a>
                    </b>
                </h4>
                <div>
                    <p style="color: gray;word-wrap: break-word;">
                        {{ article.content|slice:'100' }}...
                    </p>
                </div>
                <p>
                    <span style="color: mediumpurple;">
                        <i class="fas fa-eye" style="color: mediumpurple;"></i>
                        {{ article.total_views }} &nbsp;&nbsp;&nbsp;
                    </span>
                    <span style="color: cornflowerblue;">
                        <i class="fas fa-comments" style="color: cornflowerblue;"></i>
                        {{ article.comments.count }} &nbsp;&nbsp;&nbsp;
                    </span>
                    <span style="color: mediumpurple;">
                        <i class="fas fa-clock" style="color: mediumpurple;"></i>
                        {{ article.created|timesince_zh }} &nbsp;&nbsp;&nbsp;
                    </span>
                </p>
            </div>
            <hr style="width: 100%;"/>
        {% endfor %}
    </div>
        <div class="pagination row">
            <div class="m-auto">
            <span class="step-links">
                {% if articles.has_previous %}
                    <a href="?page=1&order={{ order }}&search={{ search }}&column={{ column }}&tag={{ tag }}" class="btn btn-success">&laquo; 1</a>
                    <span>...</span>
                    <a href="?page={{ articles.previous_page_number }}&order={{ order }}&search={{ search }}&column={{ column }}&tag={{ tag }}" class="btn btn-secondary">
                    {{ articles.previous_page_number }}
                </a>
                {% endif %}
                <span class="current btn btn-danger btn-lg">
                    {{ articles.number }}
                </span>
                {% if articles.has_next %}
                    <a href="?page={{ articles.next_page_number }}&order={{ order }}&search={{ search }}&column={{ column }}&tag={{ tag }}" class="btn btn-secondary">
                        {{ articles.next_page_number }}
                    </a>
                    <span>...</span>
                    <a href="?page={{ articles.paginator.num_pages }}&order={{ order }}&search={{ search }}&column={{ column }}&tag={{ tag }}" class="btn btn-success">
                        {{ articles.paginator.num_pages }} &raquo;
                    </a>
                {% endif %}
            </span>
            </div>
        </div>
    </div>
{% endblock %}

templates/article/updata_article.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-12">
                <form method="POST" action=".">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="title" class="form-label">文章标题</label>
                        <input type="text" class="form-control" id="title" name="title" value="{{article.title}}">
                    </div>
                    <br>
                    <div class="form-group">
                        <label for="column">栏目</label>
                        <select class="form-select" id="column" name="column">
                            {% if article.column.id %}
                                <option value="{{ article.column.id }}" selected>{{ article.column }}</option>
                                <option value="none">请选择栏目...</option>
                                {% for column in columns %}
                                    {% if column.id != article.column.id %}
                                        <option value="{{ column.id }}">
                                            {{ column }}
                                        </option>
                                    {% endif %}
                                {% endfor %}
                            {% else %}
                                <option value="none">请选择栏目...</option>
                                {% for column in columns %}
                                    <option value="{{ column.id }}">
                                        {{ column }}
                                    </option>
                                {% endfor %}
                            {% endif %}

                        </select>
                    </div>
                    <br>
                    <div class="form-group">
                        <label for="tags">标签</label>
                        <input type="text" class="form-control col-3" id="tags" name="tags" value="{{ tags }}">
                    </div>
                    <br>
                    <div class="form-group">
                        <label for="content" class="form-label">文章内容</label>
                        {{ article_form.media }}
                        {{ article_form.content }}
                    </div>
                    <br>
                    <button type="submit" class="btn btn-primary">提交</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}